### ISSUE TITLE
New releases?

### ISSUE THREAD

**Issue by credmond** [TestFX/Monocle#100]
Can we get new versions of Monocle or is there any reason not to provide them?

**Comment by iriikoad** [comment]
Maybe this can be useful: [see my comment here](https://github.com/TestFX/Monocle/issues/99#issuecomment-1926586710)

**Comment by credmond** [comment]
Hi -- yes, I was actually alreadsy using that already based on your comment -- thank you. But overall, the project owners should be keeping the project up to date / relevant (JavaFX really cannot afford _another_ dead ecosystem app...)

**Comment by hastebrot** [comment]
Hey, I setup this repo 10 years ago, and at this point don't even remember why it was needed. Maybe it's needed to run tests in headless environments (i.e. without a window manager) and for some reason JavaFX distribution does not provide it? The code is not by the TestFX contributors but by Oracle. You can probably just copy the latest Monocle code from a OpenJFX repository into your project (GPL classpath exception).

What I can do is update the README and add a link to updated code and artifacts. Professionally I only needed JavaFX for Java 8 which was released in March 2014.

**Comment by credmond** [comment]
Hey, thanks for the reply. Yes, that's the reason it was required; running TestFX tests in headless.

I think people are used to just grabbing this project from Maven. So rather than putting binaries in each project, I was wondering how we can update Maven. There are instructions in the README.md, but none of us will have access to do that...

**Comment by hastebrot** [comment]
The binaries are uploaded to maven central [1] as `org.testfx:openjfx-monocle`. I don't have access anymore and would not have resources to test it properly. Also Bintray does not exists anymore, JCenter does not accept new submissions, and `maven.pkg.github.com` seems to be something nobody in the Java world uses.

I'll speak with @svenruppert and @mvsoder. If applicable, I'll add a notice on the top of the readme that says it's abandoned and add a link to #99 and [2].

[1] https://mvnrepository.com/artifact/org.testfx/openjfx-monocle
[2] https://repo.maven.apache.org/maven2/one/jpro/openjfx-monocle/jfx-21/

**Comment by credmond** [comment]
> The binaries are uploaded to maven central [1] as `org.testfx:openjfx-monocle`.

Yep, but I mean it would be ideal if the newer versions were added _there_ given it's a well established project under org.testfx that everyone already knows about. I don't really think much or any testing is needed, it's just about taking Monocle from a JDK and putting it on Maven, I assume.

Is there not someone has access that can hand the project over or was it just yourself previously?

**Comment by mvsoder** [comment]
New versions posted today. One for Java 21 coming soon.

**Comment by mvsoder** [comment]
One for JFX 21 coming soon.

**Comment by credmond** [comment]
Thanks :)

**Comment by mvsoder** [comment]
A Monocle 21 build has now been posted: https://central.sonatype.com/artifact/org.testfx/openjfx-monocle

**Comment by credmond** [comment]
Thank you!
