### ISSUE TITLE
Shift-Clicks don't work when multiselecting list entries

### ISSUE THREAD

**Issue by bbqf** [TestFX/Monocle#13]
Testcases where multipe selections are made by clickOn(item1), then press(KeyCode.SHIFT) and then clickOn(item2) are failing with Monocle, while working normally under plain JavaFX. The generated screenshots show that only item2 is marked, meaning press(KeyCode.SHIFT) seems to have no effect in Monocle.

**Comment by belu** [comment]
Same problem here.

As a side note: Shift+Down works in headless but not in headfull mode.

**Comment by belu** [comment]
Furthermore it is not possible to select multiple items in headless mode with CONTROL+click.

**Comment by check1234** [comment]
Same with some keyboard events such as type(KeyCode.NUMPAD1).
It seems many of the keyboard events are not being caught by monocle!?

**Comment by tomsontom** [comment]
The reason is that key-modifiers are not passed from monocle to the other layers - I've provide a pull request - https://github.com/TestFX/Monocle/pull/48

**Comment by ribosradagast** [comment]
any progress / traction on this issue, anyone?

**Comment by belu** [comment]
@ribosradagast There is some progress going on:
https://github.com/openjdk/jfx/pull/170

**Comment by mvsoder** [comment]
Please note that this is not the 'official' Monocle repository. This repository is only for generating builds to support TestFX. To report bugs for Monocle, please visit, https://github.com/openjdk/jfx, and read the section on Issue Tracking.
