### ISSUE TITLE
how to set headless screen's width and height

### ISSUE THREAD

**Issue by marlondu** [TestFX/Monocle#16]
the default is 1280x800 , but I want to change it to 1080x1920, could I? and how?

**Comment by hastebrot** [comment]
The `HeadlessScreen` is initialized in [1]. Seems you can use the `headless.geometry` command argument to override the default screen dimensions, i.e. `-Dheadless.geometry=800x600`.

[1] https://github.com/TestFX/Monocle/blob/8u76-b04/src/main/java/com/sun/glass/ui/monocle/HeadlessScreen.java#L47-L73

**Comment by marlondu** [comment]
thank you very much. you've helped me a lot
