### ISSUE TITLE
MonacleView needs to implement _getNativeFrameBuffer(long)

### ISSUE THREAD

**Issue by jgangemi** [TestFX/Monocle#4]
i'm guessing some kind of change was made to the latest version of the java 8 sdk

```
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

that is causing the current monacle library to break.

the current released version yield this exception w/ the fore mentioned jdk

```
java.lang.AbstractMethodError: com.sun.glass.ui.View._getNativeFrameBuffer(J)I
    at com.sun.glass.ui.View.getNativeFrameBuffer(View.java:755)
    at com.sun.prism.PresentableState.lock(PresentableState.java:273)
    at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:65)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
    at java.lang.Thread.run(Thread.java:745)
```

i tried recompiling the library, but i get this error

```
/Users/jgangemi/projects/scriptkitty/git-clone/Monocle/src/main/java/com/sun/glass/ui/monocle/MonocleView.java:36: error: MonocleView is not abstract and does not override abstract method _getNativeFrameBuffer(long) in View
public final class MonocleView extends View {
             ^
Note: /Users/jgangemi/projects/scriptkitty/git-clone/Monocle/src/main/java/com/sun/glass/ui/monocle/linux/SysFS.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
:compileJava FAILED
```

it seems an implementation of `_getNativeFrameBuffer(long)` is needed but unfortunately i don't know what that should look like.

**Comment by hollingsworthd** [comment]
Based on tip from OpenJFX project it should just return zero. However, taking in their latest will break compatibility with older JREs because the @override annotation causes a compilation error.

**Comment by belu** [comment]
When using openjdk-monocle 1.8.0_20 you should use Java 1.8.0 Update 20 as runtime.

There have been some (internal) changes to 1.8.0 Update 40 which seem to break compatibility. In this case you should use the 1.8.0 Update 40 code (unfortunately this is not available as a Maven dependency but can be downloaded manually aa described in "Manual update").

**Comment by jgangemi** [comment]
yeah - that's not going to work for me as i have a requirement to be on the latest version of the jdk. kudos to oracle for introducing breaking changes in bug fix releases. 

thanks for looking into this!!

**Comment by hastebrot** [comment]
I'll prepare new releases with compatibility to newer JDK versions. Will propably name them e.g. `20151210-jdk8u20` and so on. This allows to later release versions with custom changes. Also, JDK 9 will introduce a new versioning scheme [1] [2].

The version scheme for TestFX probably also needs to have suffixes (like `-jdk8` and `-jdk9`), because JDK 9 will introduce some backward incompatible changes and we need to provide binaries for both JDK 8 and 9.

[1] https://blogs.oracle.com/java-platform-group/entry/a_new_jdk_9_version
[2] http://openjdk.java.net/jeps/223

**Comment by wimdeblauwe** [comment]
Are those release been made? I am currently using version 1.8.0_20 like this:

    <dependency>
        <groupId>org.jfxtras</groupId>
        <artifactId>openjfx-monocle</artifactId>
        <version>1.8.0_20</version>
        <scope>test</scope>
    </dependency>

But I get this same exception (`java.lang.AbstractMethodError: com.sun.glass.ui.View._getNativeFrameBuffer(J)I`) when running through Maven. Maven version:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /Users/wdb/.sdkman/candidates/maven/current
Java version: 1.8.0_92, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"
```

I don't have it when I run that same test in my IDE (IntelliJ IDEA), also in headless mode.

**Comment by wimdeblauwe** [comment]
Update to my previous comment: I managed to avoid the `AbstractMethodError` by adding the following to the `<argLine/>` of the Maven surefire plugin:
```
-Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw
```

**Comment by localmaxima** [comment]
@wimdeblauwe Many thanks, it worked for me, really appreciated
