### ISSUE TITLE
No module name specified, and automatic module name is invalid

### ISSUE THREAD

**Issue by SamCarlberg** [TestFX/Monocle#61]
The monocle releases for 9 and 11 cannot be used in a project with a `module-info.java` file due to the JAR file names being automatically resolved to invalid names - `openjfx.monocle.jdk.9.181` and `openjfx.monocle.jdk.11.23`, respectively - and because there is no `module-info` file or `Automatic-Module-Name` attribute in the manifest file.

The easiest solution would be to add this line to the JAR manifest attributes in the `build.gradle` file:

```groovy
"Automatic-Module-Name": "org.testfx.monocle" // or whatever you want the module name to be
```

**Comment by brcolow** [comment]
Thank you for reporting this - I will fix this and make a new release soon.
