### ISSUE TITLE
Monocle support for JavaFX 12

### ISSUE THREAD

**Issue by fzdy1914** [TestFX/Monocle#65]
Monocle does not support JavaFX 12 using JDK 11.

**Comment by brcolow** [comment]
Just released version `12+14` so this should now be working. Although I set the language level to 12 so I wonder if using JDK 11 with JavaFX 12 works or if I should have left the language level at 11? If you would test it that would be great. If it doesn't work I can make a new release for, say, 12.0.1 and down-grade the language level.

**Comment by fzdy1914** [comment]
Using JDK 11 will throw` java.lang.UnsupportedClassVersionError`, I am afraid that you need to release a separate version for JDK 11.

**Comment by brcolow** [comment]
I sorta figured that was a dumb idea on my part. I'm so used to the two parts being coupled. Really one could even set the language level to 9 I think because JavaFX uses no language features above that, IIRC.

I will make a new release, for version 12.0.1, tomorrow.

**Comment by brcolow** [comment]
New version, 12.0.1+2 has just been released. Give it up to 24 hours to sync.

**Comment by fzdy1914** [comment]
I have tested and it works.
Thanks for your help.
