### ISSUE TITLE
Can we port this to Android ?

### ISSUE THREAD

**Issue by beshoo** [TestFX/Monocle#75]
Dear support.
I am an android developer, and I am struggling with one matter. 
How to run headless webview on an android application.

as you know, android has webview support. 
But once app gos to the background, android will pause all UI threads including the webview itself. 

And we can not set UI thread in a service. To run in in the background. I need something like phantomjs, a browser not curl, wget.
Chrome does not support headless in the Android base, that what chromium group tells me.

I found that JavaFX has webview and it may support headless mode. 
but I note monocle has not ported to the Android system yet, base on the doc. 

**https://wiki.openjdk.java.net/display/OpenJFX/Monocle**
```
What's not done yet:
Android port
DirectFB port
```
I contact support@gluonhq.com asking for a piece of advice in this regards, they saide:

>Thanks for contacting us,
> Maybe you try with TestFX https://github.com/TestFX/TestFX, as that will let you launch headlessly a stage with a JavaFX WebView.
> 
> The version for Java 8 can also be ported to Android. But we haven't really tested what you want to accomplish, and we can't say for sure if the headless mode will work on Android (even with the app running on the foreground).
> 
> Best regards,
> Jose
> Gluon

Is there any update for Android?

kindly may you advise me if there any way to embedded headless support in my apk... Or it is impossible...

**Comment by brcolow** [comment]
There are quite a few classes inside Monocle that are meant for Android, for example:

https://github.com/TestFX/Monocle/blob/master/src/main/java/com/sun/glass/ui/monocle/AndroidAcceleratedScreen.java
https://github.com/TestFX/Monocle/blob/master/src/main/java/com/sun/glass/ui/monocle/AndroidInputDevice.java
https://github.com/TestFX/Monocle/blob/master/src/main/java/com/sun/glass/ui/monocle/AndroidInputDeviceRegistry.java

etc.

I am not sure that anyone besides the original developer who created those files has actually tried using headless Monocle on Android, but it would definitely be an interesting experiment. What have you tried so far?

**Comment by beshoo** [comment]
I tried to import the lib to Android studio but it failed to build, and there is no clear doc how to do that step by step to chive Headless mode in a service.

it seems a brand new subject. even google has no support for headless in android!
Well, I cannot see how that is true. android can run background service, then it can run headless service as well.

Regarding Monocle, and availability of Android classes, I know that and that why I open this issue.
I believe there is hope for this to become a true story.

**Comment by mvsoder** [comment]
These Monocle builds should be platform agnostic, since they do not include any native code. I would be interested to see if anyone has since been able to get headless testing working for Android developers.
