### ISSUE TITLE
Version 1.8.0_212 doesn't work

### ISSUE THREAD

**Issue by FlorianKirmaier** [TestFX/Monocle#78]
The latest version, of Oracle Java doesn't work properly with the latest Java8 release.

I've created a fix in my own fork, because i require it for JPro: https://github.com/FlorianKirmaier/Monocle/tree/8_212

I've published it on my own repository, it can be used the following way in gradle:
```
    repositories {
        maven {
            url "http://sandec.bintray.com/repo"
        }
    }

    dependencies {
        compile "de.sandec:openjfx-monocle:8u212"
    }
```

**Comment by allesio** [comment]
After upgrading to 8.212 it's not working for me as well:
`java.lang.AbstractMethodError: com.sun.glass.ui.Timer._pause(J)V
	at com.sun.glass.ui.Timer.pause(Timer.java:141)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pauseTimer(QuantumToolkit.java:500)
	at com.sun.javafx.tk.quantum.QuantumToolkit.postPulse(QuantumToolkit.java:487)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$409(QuantumToolkit.java:343)
	at com.sun.glass.ui.monocle.MonocleTimer$1.run(MonocleTimer.java:58)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)`

I saw there was similar problem with jdk12, ... 

It would be nice if it will be fixed for 8 as well, for now thanks Florian for workaround.

**Comment by jbeckers** [comment]
If anyone's looking: I made this work with jdk8u311 in https://github.com/jbeckers/Monocle

**Comment by lama-akeila** [comment]
> If anyone's looking: I made this work with jdk8u311 in https://github.com/jbeckers/Monocle

Im interested.. I"ve been having issue running my headless tests with 8u311.. Im currently using 
    testCompile 'org.testfx:testfx-core:4.0.16-alpha'
    testCompile 'org.testfx:openjfx-monocle:8u76-b04'
    testCompile 'org.testfx:testfx-junit:4.0.15-alpha'

and it running the build in headless mode produces the following error and the build hangs... It works on JDK 8 version 211 and earlier:
<code>
8:21:13.325 [DEBUG] [TestEventLogger]     java.lang.NoSuchMethodException: com.sun.glass.ui.Screen.<init>(long, int, int, int, int, int, int, int, int, int, int, int, float)
18:21:13.326 [DEBUG] [TestEventLogger]     	at java.lang.Class.getConstructor0(Class.java:3082)
18:21:13.326 [DEBUG] [TestEventLogger]     	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
18:21:13.326 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication$2.run(MonocleApplication.java:234)
18:21:13.326 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication$2.run(MonocleApplication.java:230)
18:21:13.326 [DEBUG] [TestEventLogger]     	at java.security.AccessController.doPrivileged(Native Method)
18:21:13.326 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.MonocleApplication.staticScreen_getScreens(MonocleApplication.java:229)
18:21:13.326 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.Screen.initScreens(Screen.java:412)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.Application.lambda$run$1(Application.java:155)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:47)
18:21:13.327 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:748)
18:21:13.327 [DEBUG] [TestEventLogger]     Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.javafx.tk.quantum.QuantumToolkit.assignScreensAdapters(QuantumToolkit.java:729)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.javafx.tk.quantum.QuantumToolkit.runToolkit(QuantumToolkit.java:334)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$startup$10(QuantumToolkit.java:279)
18:21:13.327 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.Application.lambda$run$1(Application.java:156)
18:21:13.328 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:77)
18:21:13.328 [DEBUG] [TestEventLogger]     	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:47)
18:21:13.328 [DEBUG] [TestEventLogger]     	at java.lang.Thread.run(Thread.java:748)
</code>

**Comment by lama-akeila** [comment]
> If anyone's looking: I made this work with jdk8u311 in https://github.com/jbeckers/Monocle

@jbeckers 
MonocleApplication.java needs to be fixed. The staticScreen_getScreens() method needs to define the correct constructor with 20 parameters for com.sun.glass.ui.Screen.java.

Constructor c = AccessController.doPrivileged( new PrivilegedAction<Constructor>() { @Override public Constructor run() { try { Constructor c = Screen.class.getDeclaredConstructor( Long.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Integer.TYPE, Float.TYPE, Float.TYPE, Float.TYPE, Float.TYPE);

and it needs to be instantiated with the 20 parameters. Currently it only has 13 parameters which creates the above error.

**Comment by jbeckers** [comment]
Thanks, fixed now.

I should clarify: when I said I made this work, I meant 'compile' :-)

**Comment by lama-akeila** [comment]
Great :)

**Comment by mvsoder** [comment]
A new Monocle buidl for 8.0.372 was released yesterday: https://central.sonatype.com/artifact/org.testfx/openjfx-monocle/versions
