### ISSUE TITLE
Changes to make Monocle compatible with every Java 8 version

### ISSUE THREAD

**Issue by hollingsworthd** [TestFX/Monocle#9]
FYI: here are some revisions to Monocle which makes it compatible with every version of Java 8, https://github.com/MachinePublishers/jBrowserDriver/commit/944c7c5c35ea5779dedbe0fba434c099c313d6c4

**Comment by mvsoder** [comment]
This repository is simply a copy of the official Monocle code found in the JFX repository: https://github.com/openjdk/jfx. We only maintain this repository for purposes of building the library to support headless testing with TestFX. Our apologies. However, builds for JDK 8.0.372 have recently been posted: https://central.sonatype.com/artifact/org.testfx/openjfx-monocle/versions
