### ISSUE TITLE
Confusing error message when drawing outside the screen

### ISSUE THREAD

**Issue by kiPPei123** [TestFX/Monocle#96]
When using a stage that is too large and/or headless screen that is too small, BufferOverflowException is thrown without any details pointing to the root cause of the problem. This leads to bug reports like https://github.com/TestFX/Monocle/issues/56.

A clearer error message would be great.

**Comment by mvsoder** [comment]
This repository is simply a copy of the official Monocle code found in the JFX repository: https://github.com/openjdk/jfx. We only maintain this repository for purposes of building the library to support headless testing with TestFX. Our apologies.
